// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYUK8EioCEDZCpKSTADCUcFvTFRf4mVw',
    appId: '1:520773754182:android:285b64d2fdcff50a135947',
    messagingSenderId: '520773754182',
    projectId: 'fashion-app-89568',
    storageBucket: 'fashion-app-89568.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXkD2a5kxUeIDsuE2kCBXVvaEHUXu1QS0',
    appId: '1:520773754182:ios:dcb477f7ebba596d135947',
    messagingSenderId: '520773754182',
    projectId: 'fashion-app-89568',
    storageBucket: 'fashion-app-89568.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXkD2a5kxUeIDsuE2kCBXVvaEHUXu1QS0',
    appId: '1:520773754182:ios:dcb477f7ebba596d135947',
    messagingSenderId: '520773754182',
    projectId: 'fashion-app-89568',
    storageBucket: 'fashion-app-89568.firebasestorage.app',
    iosBundleId: 'com.example.fashionApp',
  );
}
